/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_1 (
    input [0:0] a,
    input [0:0] b,
    input [0:0] c,
    output reg [1:0] out
  );
  
  
  
  always @* begin
    out = a + b + c;
  end
endmodule
