/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu8_testcases_8 (
    input [2:0] count,
    output reg [5:0] alufn,
    output reg [95:0] testcases,
    output reg [1:0] state
  );
  
  
  
  reg [95:0] cases;
  
  always @* begin
    alufn = 6'h00;
    cases = 96'h000000000000000000000000;
    state[0+1-:2] = 1'h0;
    
    case (count)
      4'h0: begin
        alufn = 6'h00;
        cases = 96'h000000000000000000000000;
        state[1+0-:1] = 1'h1;
      end
      4'h1: begin
        alufn = 6'h01;
        cases = 96'h010001070205040202060501;
        state[0+0-:1] = 1'h1;
      end
    endcase
    testcases = cases;
  end
endmodule
