/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adc_to_leds_3 (
    input clk,
    input rst,
    output reg [3:0] channel,
    input [9:0] sample,
    input [3:0] sample_channel,
    input new_sample,
    output reg [7:0] leds
  );
  
  
  
  localparam LED_TO_CHANNEL = 40'h9876543210;
  
  localparam CHANNEL_TO_LED = 64'bxxxxxxxxxxxxxxxxxxxxxxxx011101100101010000110010xxxxxxxx00010000;
  
  wire [(4'h8+0)-1:0] M_pwm_pulse;
  reg [(4'h8+0)*10-1:0] M_pwm_value;
  reg [(4'h8+0)-1:0] M_pwm_update;
  
  genvar GEN_pwm0;
  generate
  for (GEN_pwm0=0;GEN_pwm0<4'h8;GEN_pwm0=GEN_pwm0+1) begin: pwm_gen_0
    pwm_8 pwm (
      .clk(clk),
      .rst(rst),
      .value(M_pwm_value[GEN_pwm0*(4'ha)+(4'ha)-1-:(4'ha)]),
      .update(M_pwm_update[GEN_pwm0*(1)+(1)-1-:(1)]),
      .pulse(M_pwm_pulse[GEN_pwm0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  reg [3:0] M_ch_d, M_ch_q = 1'h0;
  
  always @* begin
    M_ch_d = M_ch_q;
    
    channel = LED_TO_CHANNEL[(M_ch_q)*4+3-:4];
    M_pwm_value = {4'h8{{sample}}};
    M_pwm_update = 8'h00;
    if (new_sample) begin
      M_pwm_update[(CHANNEL_TO_LED[(sample_channel)*4+3-:4])*1+0-:1] = 1'h1;
      M_ch_d = M_ch_q + 1'h1;
      if (M_ch_q == 3'h7) begin
        M_ch_d = 1'h0;
      end
    end
    leds = M_pwm_pulse;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ch_q <= 1'h0;
    end else begin
      M_ch_q <= M_ch_d;
    end
  end
  
endmodule
