/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_arith8_3 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg [7:0] arith,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [7:0] temp_arith;
  
  reg [7:0] xb;
  
  always @* begin
    temp_arith = 1'h0;
    xb = b ^ {4'h8{alufn[0+0-:1]}};
    temp_arith = a + xb + alufn[0+0-:1];
    if (alufn[0+1-:2] == 2'h2) begin
      temp_arith = a * b;
    end
    z = (temp_arith == 8'h00);
    v = ((a[7+0-:1] & xb[7+0-:1] & !temp_arith[7+0-:1]) || (!a[7+0-:1] & !xb[7+0-:1] & temp_arith[7+0-:1]));
    n = temp_arith[7+0-:1];
    arith = temp_arith;
  end
endmodule
