/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [5:0] opcode;
  
  reg [7:0] out;
  
  wire [8-1:0] M_adder_s;
  reg [8-1:0] M_adder_a;
  reg [8-1:0] M_adder_b;
  reg [6-1:0] M_adder_alufn;
  adder8_1 adder (
    .a(M_adder_a),
    .b(M_adder_b),
    .alufn(M_adder_alufn),
    .s(M_adder_s)
  );
  
  wire [8-1:0] M_bool_s;
  reg [8-1:0] M_bool_a;
  reg [8-1:0] M_bool_b;
  reg [6-1:0] M_bool_alufn;
  bool8_2 bool (
    .a(M_bool_a),
    .b(M_bool_b),
    .alufn(M_bool_alufn),
    .s(M_bool_s)
  );
  
  wire [8-1:0] M_shift_z;
  reg [8-1:0] M_shift_a;
  reg [3-1:0] M_shift_b;
  reg [6-1:0] M_shift_alufn;
  shift8_3 shift (
    .a(M_shift_a),
    .b(M_shift_b),
    .alufn(M_shift_alufn),
    .z(M_shift_z)
  );
  
  wire [8-1:0] M_cmp_cmp;
  reg [8-1:0] M_cmp_a;
  reg [8-1:0] M_cmp_b;
  reg [6-1:0] M_cmp_alufn;
  cmp8_4 cmp (
    .a(M_cmp_a),
    .b(M_cmp_b),
    .alufn(M_cmp_alufn),
    .cmp(M_cmp_cmp)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_5 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    opcode = io_dip[16+0+5-:6];
    M_adder_a = io_dip[0+7-:8];
    M_adder_b = io_dip[8+7-:8];
    M_adder_alufn = io_dip[16+0+5-:6];
    M_bool_a = io_dip[0+7-:8];
    M_bool_b = io_dip[8+7-:8];
    M_bool_alufn = io_dip[16+0+5-:6];
    M_shift_a = io_dip[0+7-:8];
    M_shift_b = io_dip[8+0+2-:3];
    M_shift_alufn = io_dip[16+0+5-:6];
    M_cmp_a = io_dip[0+7-:8];
    M_cmp_b = io_dip[8+7-:8];
    M_cmp_alufn = io_dip[16+0+5-:6];
    out = 1'h0;
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    
    case (opcode[4+1-:2])
      1'h0: begin
        out = M_adder_s;
      end
      1'h1: begin
        out = M_bool_s;
      end
      4'ha: begin
        out = M_shift_z;
      end
      4'hb: begin
        out = M_cmp_cmp;
      end
    endcase
    io_led[0+7-:8] = out;
  end
endmodule
